export default {
  INIT: 'INIT',
  GET_I18N: 'GET_I18N',
  FETCH_CITIES: 'FETCH_CITIES',
  FETCH_STYLES: 'FETCH_STYLES',
  GET_FORM_OPTIONS: 'GET_FORM_OPTIONS',
  MUTATE_FORM_OPTIONS: 'MUTATE_FORM_OPTIONS',

  GET_FORM_VALUE: 'GET_FORM_VALUE',
  SET_FORM_VALUE: 'SET_FORM_VALUE',
  MUTATE_FORM_VALUE: 'MUTATE_FORM_VALUE',
  GET_FORM_IS_DISABLED: 'GET_FORM_IS_DISABLED',
  MUTATE_POSTER_IS_LOADED: 'MUTATE_POSTER_IS_LOADED',
  MUTATE_AUDIO_IS_LOADED: 'MUTATE_AUDIO_IS_LOADED',
  UPLOAD_AUDIO: 'UPLOAD_AUDIO',
  UPLOAD_POSTER: 'UPLOAD_POSTER',
  SUBMIT_FORM: 'SUBMIT_FORM',
};
