export default {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
  MUTATE_POSITION: 'MUTATE_POSITION',
  MUTATE_COMPONENT: 'MUTATE_COMPONENT',
  GET_POSITION: 'GET_POSITION',
  GET_COMPONENT: 'GET_COMPONENT',
};
